spring.application.name=BankApp
server.port=8081
# ===========================
# Oracle DB Configuration
# ===========================
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XE
#spring.datasource.url=jdbc:oracle:thin:@//host.docker.internal:1521/XE
spring.datasource.username=system
spring.datasource.password=tiger2
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update

spring.datasource.hikari.initialization-fail-timeout=60000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000
#spring.jpa.hibernate.ddl-auto=create-drop  
# Use 'validate' or 'create' in production

# ===========================
# JWT
# ===========================
jwt.secret=b8fFzXrE7sW9tY2vQ1uK9rM5cT8hN0aPvQ7yXrD4eP9zW3uL2nK5sT6rQ9aY0xNc
jwt.expiration=86400000   
# 24 hours in ms

# ===========================
# Logging
# ===========================
logging.level.org.springframework=INFO
